CREATE DATABASE IF NOT EXISTS BD_APP_MUSICAS;
USE BD_APP_MUSICAS;
CREATE TABLE IF NOT EXISTS ARTISTA(
	CPF VARCHAR(11) PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    TELEFONE VARCHAR(9) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL
);
CREATE TABLE IF NOT EXISTS GENERO(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    RITIMO VARCHAR(150) NOT NULL,
    ESTILO VARCHAR(155) NOT NULL
);
CREATE TABLE IF NOT EXISTS ALBUM(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    TEMPO TIMESTAMP,
    FK_ARTISTA_CPF VARCHAR(11),
    FOREIGN KEY (FK_ARTISTA_CPF) REFERENCES ARTISTA(CPF)
);
CREATE TABLE IF NOT EXISTS FAIXA(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    OUVINTES INT NOT NULL,
    NOME VARCHAR(100) NOT NULL,
	DURACAO DOUBLE NOT NULL,
    FK_ALBUM_ID INT,
    FK_GENERO_ID INT,
    FOREIGN KEY (FK_ALBUM_ID) REFERENCES ALBUM(ID) ,
    FOREIGN KEY (FK_GENERO_ID) REFERENCES GENERO(ID)
    
);